name: deafrica-waterbodies-env
channels:
  - conda-forge
dependencies:
  - python = 3.10.6 
  - gdal = 3.6.3 
  - pip:
    - --extra-index-url="https://packages.dea.ga.gov.au"
    - pip-tools
    - numpy
    - pandas 
    - geopandas
    - python-geohash
    - datacube
    - shapely
    - click
    - fsspec
    - boto3
    - botocore
    - rasterio
    - s3urls
    - python-dateutil
    - deafrica-tools >= 2.0.3
    # Code style
    - flake8
    - black
    # Testing
    - pytest
    
