name: Test

on: [push]

env:
  ORG: digitalearthafrica
  IMAGE: deafrica-waterbodies
  PRODUCT_CATALOG: https://raw.githubusercontent.com/digitalearthafrica/config/master/prod/products_prod.csv

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      
    - name: Activate Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11  
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Setup deafrica-waterbodies test environment
      run: |
          make test-env
    
    - name: Run deafrica-waterbodies test
      run: |
          docker-compose exec -T waterbodies bash -c "pytest ."
      
    
